#!/bin/sh

case "$1" in
    start)
        grep -E '^\w+$' < /etc/default/modules | sort | uniq | \
            while read -r mod; do
                if modprobe "$mod"; then
                    echo "Loaded module $mod"
                else
                    echo "FAILED to load module $mod" >&2
                fi
            done
        ;;

    stop)
        ;;

    *)
        echo "Usage: $0 start" >&2
        exit 1
        ;;
esac
