#!/bin/sh

NAME="dhcprelay"
DAEMON="/usr/sbin/${NAME}"
CFG_FILE="/etc/conf.d/${NAME}"

source "$CFG_FILE"

case "$1" in
        start)
        printf "Starting ${NAME}: "
        start-stop-daemon -S -b -q -x "${DAEMON}" -- "$CLIENT_IFACE" "$SERVER_IFACE"
        [ $? = 0 ] && echo "OK" || echo "FAIL" >&2
                ;;
        stop)
        printf "Stopping ${NAME}: "
        start-stop-daemon -K -q -n "${NAME}"
        [ $? = 0 ] && echo "OK" || echo "FAIL" >&2
                ;;
        restart|reload)
        echo "Restarting $NAME: "
        $0 stop
        sleep 1
        $0 start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}" >&2
                exit 1
                ;;
esac
